### PR TITLE
Added links to website, preprint and google form :)

### PR DESCRIPTION
**Pull request by helenahartmann**

### CODE REVIEW

**Review by caggursoy — APPROVED** [review]
Nice changes. Maybe in the future we need to have a PR template too

**Comment by helenahartmann** [comment]
yes please, as it includes the links!

**Comment by helenahartmann** [comment]
you might need to change the google form links and add your new stuff.

**Comment by caggursoy** [comment]
@mamuerie @alkastrinogiannis would introducing changes on the .md files create any issues?

**Review by alkastrinogiannis — APPROVED** [review]

**Pull request merged**
